name: tech_cuttie
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_launcher_icons: ^0.9.2

  firebase_auth: ^3.1.2
  firebase_dynamic_links: ^2.0.10
  firebase_core: ^1.7.0
  url_launcher: ^6.0.12
  lint: ^1.7.2

  contactus: ^1.2.0

  about: ^2.0.1
  material_floating_search_bar: ^0.3.4
  cloud_firestore: ^2.5.3
  intl: ^0.17.0
  get: ^4.3.8
  animations: ^2.0.1
  provider: ^6.0.1
  share: ^2.0.4
  firebase_storage: ^10.0.5
  image_picker: ^0.8.4+2
  video_player: ^2.2.5
  path: ^1.8.0
  http: ^0.13.4
  html: ^0.15.0
  wordpress_api: ^1.2.0
  flutter_html: ^2.1.4
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading.gif
    - assets/images/user_loading.gif
    - assets/images/tech_cuttie_logo.png
